name: Generate Snake Contribution Graph

on:
  schedule: # every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake.svg and snake.gif
        uses: Platane/snk@v3
        with:
          github_user_name: samanhappy
          outputs: |
            dist/snake.svg
            dist/snake.gif
            dist/snake-dark.svg
            dist/snake-dark.gif

      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

